### ISSUE TITLE
Asking to Authorize again After system Reboot

### ISSUE THREAD

**Issue by sheminasalam** [w35l3y/hassio-addons#18]
I have been using this addon without any issues for a longtime. But today I noticed that the addon stops working after there is a system reboot. when I checked the addon logs, I could see that it was asking to authorize with cloudflare again. The following is the log.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/cloudflare.sh
Validating rules from /data/options.json
OK
Checking certificate...
Logging...
Please open the following URL and log in with your Cloudflare account:
https://dash.cloudflare.com/argotunnel?callback=https%************************************%3D
Leave cloudflared running to download the cert automatically.
2022-08-27T01:14:44Z INF Waiting for login...
2022-08-27T01:15:38Z INF Waiting for login...
```

Once I completed authorization again, it worked without any issues till the system is restarted.
Also what does this mean. I found it in logs.

```
WRN Your version 2022.5.1 is outdated. We recommend upgrading it to 2022.8.2
```

**Comment by w35l3y** [comment]
> I noticed that the addon stops working after there is a system reboot.

How is your configuration?
This should happen if you have `url` defined, for example.
Make sure to ommit sensitive data before posting here.

> WRN Your version 2022.5.1 is outdated.

Just rebuild and it should update to the latest version.

![Screenshot_20220827-032132_Samsung Internet](https://user-images.githubusercontent.com/963510/187017875-55744389-4cba-4efa-95cd-06768b412d96.jpg)

**Comment by sheminasalam** [comment]
After rebuilding the addon, the issue has been rectified. thanks

**Comment by sheminasalam** [comment]
This happened again.. This is my config.
```
tunnel: homeassistant
credentials-file: /data/tunnel.json
protocol: auto
origincert: /data/cert.pem
loglevel: info
transport-loglevel: warn
ingress:
  - hostname: www.******.com
    service: http://192.168.1.1:2123
  - service: http_status:404
originRequest: {}
warp-routing:
  enabled: false
metrics: localhost:41705
metrics-update-freq: 5s
grace-period: 30s
retries: 5
no-autoupdate: true
```
